version: '2'
services:
  simple-server-node:
    build: ./simple-server-node
    # Using the host's network stack inside container
    network_mode: host
    ports:
      - "80"

  wificonnect:
    build: ./resin-wifi-connect
# mmust run in priviliged mode to be able to change hostname
    privileged: true
    # Using the host's network stack inside container
    network_mode: host
    labels:
      io.resin.features.dbus: '1'
