version: '2'
services:
  frontend:
    build: ./frontend
    expose:
      - "80"
#  proxy:
#    build: ./haproxy
#    depends_on:
#      - frontend
#      - data
#    ports:
#      - "80:80"
#  data:
#    build: ./data
#    expose:
#      - "8080"
  wificonnect:
    build: ./resin-wifi-connect
# must run in priviliged mode to be able to change hostname
#    priviliged: true
