version: '2'
services:
  server:
    build: ./simple-server-node
    ports:
      - "80"

  wificonnect:
    build: ./resin-wifi-connect
# mmust run in priviliged mode to be able to change hostname
    privileged: true
    network_mode: host
    labels:
      io.resin.features.dbus: '1'
