version: '2'
services:
#  server:
#    build: ./simple-server-node
#    ports:
#      - "80"

  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.dbus: '1'
